spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 1248
    url: jdbc:mysql://192.168.100.6/sell?characterEncoding=UTF-8&useSSL=false
  jpa:
    show-sql: true
#server:
#  servlet:
#    context-path: /sell
#logging:
#  pattern:
#    console: "%d - %msg%n"
#  #path: "D:/Idea17Projects/log/tomcat/"
#  file: "D:/Idea17Projects/log/tomcat/sell.log"
#  level:
#    com.ice.sell.LoggerTest: debug